spring:
  application:
    name: tdplay

  datasource:
    url: jdbc:TAOS://127.0.0.1:6030/carrier_data?user=root&password=taosdata&charset=UTF-8
    driver-class-name: com.taosdata.jdbc.TSDBDriver
    hikari:
      connection-test-query: select server_status();
mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.example.tdplay.model
